call parse 00Attract
call parse A1Drawbridge
call parse B2DrinkMe
call parse B2Vines
call parse B2Wind
call parse B3Fire
call parse B3Pot
call parse B3Throne
call parse B4Goons
call parse B4Snakes
call parse B4Wall
call parse C5LizardKing1
call parse C5Pit1
call parse C5Ropes1
call parse C5Ropes2
call parse C6Horse1
call parse C6Horse2
call parse C6Smithy1
call parse C6Smithy2
call parse C6Wizard1
call parse C6Wizard2
call parse C7Crypt1
call parse C7Crypt2
call parse C7Knight1
call parse C7Knight2
call parse C7Pond1
call parse C7Pond2
call parse DPlatform
call parse EBats
call parse EBlackKnight
call parse ECatwalk
call parse EElectricCage
call parse EMudMen
call parse EPoolBalls
call parse ERiver
call parse EVanishingFloor
call parse FDragonsLair
